### ISSUE TITLE
AttributeError: module 'dash_draggable' has no attribute 'ResponsiveGridLayout'

### ISSUE THREAD

**Issue by isCopyman** [MehdiChelh/dash-draggable#3]

**Comment by MehdiChelh** [comment]
Hello,

Sorry for the late reply. `ResponsiveGridLayout` was available in the latest release, which was a pre-release in pypi.org when you opened the issue (and by default pip don't install prerelease version).
Now if you install the latest version (0.1.2) you should be able to import ResponsiveGridLayout.

```
pip uninstall dash_draggable
pip install dash_draggable
```

If it's ok for you then I will close the issue.
